import type { PermissionRegistryEntry } from './permission.types';

export const PERMISSION_REGISTRY = [
  {
    code: 'dashboard.view',
    module: 'dashboard',
    action: 'view',
    name: 'View dashboard',
    defaultRoles: ['admin', 'standard'],
    sortOrder: 10,
  },
  {
    code: 'user.read',
    module: 'user',
    action: 'read',
    name: 'View users',
    defaultRoles: ['admin'],
    sortOrder: 100,
  },
  {
    code: 'user.create',
    module: 'user',
    action: 'create',
    name: 'Create user',
    defaultRoles: ['admin'],
    sortOrder: 110,
  },
  {
    code: 'user.update',
    module: 'user',
    action: 'update',
    name: 'Update user',
    defaultRoles: ['admin'],
    sortOrder: 120,
  },
  {
    code: 'user.delete',
    module: 'user',
    action: 'delete',
    name: 'Delete user',
    defaultRoles: [],
    sortOrder: 130,
  },
  {
    code: 'user.assign_roles',
    module: 'user',
    action: 'assign_roles',
    name: 'Assign user roles',
    defaultRoles: ['admin'],
    sortOrder: 140,
  },
  {
    code: 'role.read',
    module: 'role',
    action: 'read',
    name: 'View roles',
    defaultRoles: ['admin'],
    sortOrder: 200,
  },
  {
    code: 'role.create',
    module: 'role',
    action: 'create',
    name: 'Create role',
    defaultRoles: [],
    sortOrder: 210,
  },
  {
    code: 'role.update',
    module: 'role',
    action: 'update',
    name: 'Update role',
    defaultRoles: [],
    sortOrder: 220,
  },
  {
    code: 'role.delete',
    module: 'role',
    action: 'delete',
    name: 'Delete role',
    defaultRoles: [],
    sortOrder: 230,
  },
  {
    code: 'role.assign_permissions',
    module: 'role',
    action: 'assign_permissions',
    name: 'Assign role permissions',
    defaultRoles: [],
    sortOrder: 240,
  },
  {
    code: 'permission.read',
    module: 'permission',
    action: 'read',
    name: 'View permissions',
    defaultRoles: ['admin'],
    sortOrder: 300,
  },
  {
    code: 'dictionary.read',
    module: 'dictionary',
    action: 'read',
    name: 'View dictionaries',
    defaultRoles: ['admin'],
    sortOrder: 400,
  },
  {
    code: 'dictionary.create',
    module: 'dictionary',
    action: 'create',
    name: 'Create dictionary',
    defaultRoles: ['admin'],
    sortOrder: 410,
  },
  {
    code: 'dictionary.update',
    module: 'dictionary',
    action: 'update',
    name: 'Update dictionary',
    defaultRoles: ['admin'],
    sortOrder: 420,
  },
  {
    code: 'dictionary.delete',
    module: 'dictionary',
    action: 'delete',
    name: 'Delete dictionary',
    defaultRoles: [],
    sortOrder: 430,
  },
  {
    code: 'file.read',
    module: 'file',
    action: 'read',
    name: 'View files',
    defaultRoles: ['admin'],
    sortOrder: 500,
  },
  {
    code: 'file.upload',
    module: 'file',
    action: 'upload',
    name: 'Upload file',
    defaultRoles: ['admin'],
    sortOrder: 510,
  },
  {
    code: 'file.update',
    module: 'file',
    action: 'update',
    name: 'Update file',
    defaultRoles: ['admin'],
    sortOrder: 520,
  },
  {
    code: 'file.delete',
    module: 'file',
    action: 'delete',
    name: 'Delete file',
    defaultRoles: [],
    sortOrder: 530,
  },
  {
    code: 'file.download',
    module: 'file',
    action: 'download',
    name: 'Download file',
    defaultRoles: ['admin'],
    sortOrder: 540,
  },
  {
    code: 'setting.read',
    module: 'setting',
    action: 'read',
    name: 'View settings',
    defaultRoles: ['admin'],
    sortOrder: 600,
  },
  {
    code: 'setting.update',
    module: 'setting',
    action: 'update',
    name: 'Update settings',
    defaultRoles: [],
    sortOrder: 610,
  },
  {
    code: 'audit_log.read',
    module: 'audit_log',
    action: 'read',
    name: 'View audit logs',
    defaultRoles: [],
    sortOrder: 700,
  },
] as const satisfies readonly PermissionRegistryEntry[];
